#!/bin/bash

#Programs to install:
# Haskell compiler etc..
sudo pacman -S cabal-install
cabal-install cabal-dev
# Python for the testsuite
sudo pacman -S python2-pip cabal-dev python2-fabric python2-requests
sudo pip2 install py-test

#Also need vagrant. If you have aura this might work
#sudo aura -Ak vagrant

#How to actually test

#1st build your changes
cabal-dev install

#then bring up the vagrant box
vagrant up

#Then run the testsuite
py.test testsuite/ -s
