application: bittolldocs
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html

- url: /contrib
  static_files: html/contrib.html
  upload: html/contrib.html

- url: /api
  static_files: html/api.html
  upload: html/api.html

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
